apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: system
spec:
  template:
    metadata:
      labels:
        node.kubernetes.io/role: system
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: "karpenter.k8s.aws/instance-memory"
          operator: Gt
          values: ["4000"]
      nodeClassRef:
        name: general
      taints:
        - key: node.kubernetes.io/role
          value: system
          effect: NoSchedule
  limits:
    cpu: "1000"
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
